version: '3.0'
services:
    mysql:
        image: mysql:5.6
        container_name: mysql-5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
        volumes: 
            - ./data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: root
        ports:
        - "3306:3306"
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
  
