version: '3.1'

services:
    redis:
        image: redis:6.2
        container_name: redis-6
        command: redis-server /data/redis.conf
        volumes: 
            - ./data:/data
        ports:
            - "6399:6399"
