version: '3.1'
 
services:
  elasticsearch:
    image: elasticsearch:7.17.6
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - somenetwork
    environment:
      - discovery.type=single-node
  kibana:
    image: kibana:7.17.6
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - somenetwork

networks:
  somenetwork:
    driver: bridge
